### ISSUE TITLE
T check validation bug.

### ISSUE THREAD

**Issue by jginsburgn** [JorgeBarMza/Conecta-T#1]
Getting error upon running repeatedly:
---
Traceback (most recent call last):
  File "judge_alt.py", line 192, in <module>
    main()
  File "judge_alt.py", line 169, in main
    while (gameFinished(turn) == 0):
  File "judge_alt.py", line 55, in gameFinished
    if (checkAnyT(player_number)):
  File "judge_alt.py", line 81, in checkAnyT
    if (checkWinBelow(r, c, player_number)
  File "judge_alt.py", line 96, in checkWinBelow
    if (board[row - 1][col + 1] == player_number and board[row][col + 1] == player_number and board[row + 1][
IndexError: list index out of range

**Comment by ChrisAAP** [comment]
The issue was caused when rows and columns were updated. This issue should be fixed now. Thank you for bringing it to our attention.
